services:
  vote:
    build: ./vote
    ports:
      - "5000:5000"
    networks:
       - voting
    depends_on:
        - redis


  redis:
     image: redis:latest
     ports:
       - "6379:6379"
     networks:
        - voting


  worker:
     build: ./worker
     networks:
       - voting
     depends_on:
        - redis
        - postgres

  postgres:
    image: postgres:15.10
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/db
    networks:
      - voting
    environment:
      - POSTGRES_PASSWORD=postgres

  result:
    build: ./result
    ports:
      - "4000:4000"
    networks:
      - voting
    depends_on:
      - postgres

networks:
   voting:
      driver: bridge

volumes:
   postgres:
     driver: local
